### ISSUE TITLE
compilation.assets["foo.meta.js"] undefined with v2.5.0

### ISSUE THREAD

**Issue by SimonAlling** [momocow/webpack-userscript#21]
I suddenly noticed that [Userscripter](https://github.com/SimonAlling/userscripter)-based userscripts [wouldn't build anymore](https://github.com/SimonAlling/userscripter/issues/15). The problem turned out to be that, [when tapping the `afterCompile` hook](https://github.com/SimonAlling/userscripter/blob/4c32737a2e45d47687afd8c77eeaa6e7aa8fec01/src/build/internal/webpack-plugin.ts#L34), `compilation.assets["bootstrapped-userscript.meta.js"]` was `undefined` (even though `compilation.assets["bootstrapped-userscript.user.js"]` was defined and the `metajs` option was `true`). However, the metadata file was still created and listed as an emitted asset by Webpack.

The problem doesn't occur if I [use `webpack-userscript` v2.4.0](https://github.com/SimonAlling/userscripter/commit/4c32737a2e45d47687afd8c77eeaa6e7aa8fec01#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R103) (or v2.3.1), so some sort of regression may have been introduced since.

**Comment by momocow** [comment]
Oops! Thank you for reporting the problem.

That reminds me about my wrong decision in **versioning** and I'm sorry to say that I just broke your webpack toolchains.

The changes in v2.5.0 does not break users of Webpack, since the configuration remains unchanged, but does break those who writes plugins to integrate with `webpack-userscript`, since the tapping hook is changed. However, I just ignored that there may be someone writing codes that depending on this plugin, so I decided it to be a minor change while it actually should be a **MAJOR** change. I'm sorry for introducing such an inconsistent behavior across both versions of the plugin.

There are two major changes in v2.5.0.
- Add [SSRI ](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)calculation while building userscripts.
    > To calculate SSRI, it might be an **async** operation for the first time it meets an URL since it has to fetch the content of an URL to calculate the SRI.
- Change the hook from `compilation.hooks.afterOptimizeChunkAssets` to `compiler.hooks.emit`
    > This change is introduced because `compilation.hooks.afterOptimizeChunkAssets` is a sync hook and the plugin requires a new place to hook which should be async as mentioned above.

    > Beside, the plugin also supports rename, e.g. renaming `index.js` to `index.user.js`, which actually copies `compilation['index.js']` to `compilation['index.user.js']` and then deletes `compilation['index.js']` under the hood.
    > Deleting an assets during compilation actually introduces other unexpected behaviors so it must be as the last operation before complete. Actually I have tried to tap into `compilation.hooks.optimizeChunkAssets` but it introduced conflicts with [TerserPlugin](https://github.com/webpack-contrib/terser-webpack-plugin) since it deleted an assets, says `compilation['index.js']`.

---

I'm also thinking about split the logic of the plugin into several hooks; that is, preparing `.user.js` and
`.meta.js` assets during compilation but delete unused assets in another hook later.

The plugin can still be improved, still works to do. Any ideas or suggestions are welcome.

To fix your plugin, you can have a try on `compiler.hooks.afterEmit`.

---

Thank you for reading!

**Comment by SimonAlling** [comment]
Thank you for the swift reply and thorough explanation! I'll see what I can do with the `afterEmit` hook.

**Comment by SimonAlling** [comment]
[Using `afterEmit` instead of `afterCompile`](https://github.com/SimonAlling/userscripter/commit/ab4df22584b0ece4dbf64e27a24e56eafe33e9e0) worked like a charm. :slightly_smiling_face:
