### ISSUE TITLE
@webrequest is not working.

### ISSUE THREAD

**Issue by CaioWzy** [momocow/webpack-userscript#22]
// @webrequest is basically a list of multiple dictionaries each one containing their own selector and their parameters like which action to take and what to include/exclude.

headers.json
```json
{
  "name": "Burlesco",
  "version": "11.18",
  "namespace": "https://burles.co/",
  "description": "Leia notícias sem ser assinante, burle o paywall",
  "author": "rodorgas & AugustoResende",
  "supportURL": "https://burles.co/",
  "icon64": "https://burles.co/userscript/icon.png",
  "grant": [
    "GM_webRequest",
    "GM_xmlhttpRequest"
  ],
  "webrequest": [
    {"selector":"*://static.folha.uol.com.br/paywall/*", "action":"cancel"}
  ]
}
```

burlesco.meta.js
```js
// ==UserScript==
// @name Burlesco
// @version 11.18
// @author rodorgas & AugustoResende
// @description Leia notícias sem ser assinante, burle o paywall
// @supportURL https://burles.co/
// @match *://*/*
// @namespace https://burles.co/
// @icon64 https://burles.co/userscript/icon.png
// @grant GM_webRequest
// @grant GM_xmlhttpRequest
// @webrequest [object Object]
// ==/UserScript==
```

Expected output:

```js
// ==UserScript==
// @name Burlesco
// @version 11.18
// @author rodorgas & AugustoResende
// @description Leia notícias sem ser assinante, burle o paywall
// @supportURL https://burles.co/
// @match *://*/*
// @namespace https://burles.co/
// @icon64 https://burles.co/userscript/icon.png
// @grant GM_webRequest
// @grant GM_xmlhttpRequest
// @webrequest [{"selector":"*://static.folha.uol.com.br/paywall/*","action":"cancel"}]
// ==/UserScript==
```

**Comment by momocow** [comment]
Hi, sorry for the very very late response 😂

Oh I don't know there's `@webRequest` tag until now, it's not even documented in any official documents. (I admit that I depend on Tampermonkey's document the most.)

Currently our header config accepts two types of values, string or array. It's quite intuitive if it's a string and if it's an array the plugin spread the values and turns it into multiple tags. It seems to conflict with the usage in `@webRequest` if this tag expects an array to be the value and the array should only be stringified instead of spread into multiple tags.

**Comment by momocow** [comment]
As https://github.com/Tampermonkey/tampermonkey/issues/397#issuecomment-299949037 says in the comment of the code block,

> `@webRequest` may have a human readable format in the future, but for now it's the stringified first argument of GM_webRequest and allow request manipulation even if the script didn't run yet.

I think providing a stringified `webRequest`config instead of a structural object makes this plugin stick close to the userscript header format as possible. We'll support the structural format only if `@webRequest` has come out with a structural format.
